src/main/java/com/github/bugtamer/models/CountryLanguage.java
package com.github.bugtamer.models;

public class CountryLanguage {

	// ATTRIBUTES

	private String  countryCode;
	private String  language;
	private boolean isOfficial;
	private double  percentage;



	// GETTINGS

	public String getCountryCode() {
		return countryCode;
	}

	public String getLanguage() {
		return language;
	}

	public boolean isOfficial() {
		return isOfficial;
	}

	public double getPercentage() {
		return percentage;
	}



	// SETTINGS

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public void setOfficial(boolean isOfficial) {
		this.isOfficial = isOfficial;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}



	// OVERRIDED METHODS (Object)

	@Override
	public String toString() {
		return String.format("cc=%s, l=%s, o=%b, p=%f", countryCode, language, isOfficial, percentage);
	}

}

src/main/java/com/github/bugtamer/controller/CityServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CityDAO;
import com.github.bugtamer.database.CountryDAO;
import com.github.bugtamer.models.City;
import com.github.bugtamer.models.Country;

@WebServlet("/cities")
public class CityServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {


		String countryCode = request.getParameter("country"); // only available from city filter form
		
		if ((countryCode != null) && ! countryCode.isEmpty()) {
			request.setAttribute("countryCodeFilter", countryCode);
			System.out.println("countryCodeFilter=" + countryCode);
		}

		String filteredQuery = getQueryFilteredByCountry(countryCode);
		String customQuery   = getCustomQuery(request);
		String query = (filteredQuery == null) ? customQuery : filteredQuery;

		request.setAttribute("path",        request.getServletPath());
		request.setAttribute("cities",      getCities(query));
		request.setAttribute("countries",   getCountries());
		request.setAttribute("customQuery", customQuery);
		request.getRequestDispatcher("cities.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		System.out.println(request.getServletPath());

		request.setAttribute("customQuery", request.getParameter("query"));
		doGet(request, response);
	}



	// LOW LEVEL IMPLEMENTATION DETAILS
	
	private String getCustomQuery(HttpServletRequest request) {
		String customQuery   = (String) request.getAttribute("customQuery");
		String defaultQuery  = "SELECT *\nFROM city\nORDER BY Name ASC";
		return (customQuery == null) ? defaultQuery : customQuery;
	}
	

	private String getQueryFilteredByCountry(String countryCodeFilter) {
		String filteredQuery = null;
		if (countryCodeFilter != null) {
			filteredQuery = String.format("SELECT * FROM city WHERE CountryCode=\"%s\" ORDER BY Name ASC",
					countryCodeFilter);
		}
		return filteredQuery;
	}


	private List<City> getCities(String query) {
		List<City> cities = null;
		try {
			cities = CityDAO.getInstance().getList(query);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return cities;
	}


	private List<Country> getCountries() {
		List<Country> countries = null;
		try {
			countries = CountryDAO.getInstance().getList();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return countries;
	}

}

src/main/java/com/github/bugtamer/controller/CountryLanguageServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CountryLanguageDAO;
import com.github.bugtamer.models.CountryLanguage;

@WebServlet("/languages")
public class CountryLanguageServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String defaultQuery;
		defaultQuery  = "SELECT *\r\nFROM countrylanguage\r\n";
		defaultQuery += "WHERE Language LIKE 'a%'\r\nORDER BY Language ASC";

		List<CountryLanguage> countryLanguages = getCountryLanguages();

		request.setAttribute("path",      request.getServletPath());
		request.setAttribute("query",     defaultQuery);
		request.setAttribute("languages", countryLanguages);
		request.getRequestDispatcher("languages.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String query = request.getParameter("query");
		List<CountryLanguage> countryLanguages = getCountryLanguages(query);

		request.setAttribute("query",     query);
		request.setAttribute("languages", countryLanguages);
		request.getRequestDispatcher("languages.jsp").forward(request, response);
	}



	// LOW LEVEL IMPLEMENTATION DETAILS

	private List<CountryLanguage> getCountryLanguages() {
		return getCountryLanguages("");
	}


	private List<CountryLanguage> getCountryLanguages(String query) {
		List<CountryLanguage> countryLanguages = null;
		try {
			if (query.isEmpty()) {
				countryLanguages = CountryLanguageDAO.getInstance().getList();
			} else {
				countryLanguages = CountryLanguageDAO.getInstance().getList(query);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return countryLanguages;
	}

}

src/main/java/com/github/bugtamer/controller/CountryServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CountryDAO;
import com.github.bugtamer.models.Country;

@WebServlet("/countries")
public class CountryServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String query = "SELECT * FROM country";
		List<Country> countries = getCountries(query);
		request.setAttribute("path",        request.getServletPath());
		request.setAttribute("countries", countries);
		request.getRequestDispatcher("countries.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		doGet(request, response);
	}



	// LOW LEVEL IMPLEMENTATION DETAILS

	private List<Country> getCountries(String query) {
		List<Country> countries = null;
		try {
			countries = CountryDAO.getInstance().getCountryWithLanguagesList();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return countries;
	}


}

src/main/java/com/github/bugtamer/controller/CustomCityQueryServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CityDAO;
import com.github.bugtamer.database.CountryDAO;
import com.github.bugtamer.models.City;
import com.github.bugtamer.models.Country;

@WebServlet("/customCityQuery")
public class CustomCityQueryServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		
		System.out.println("CustomCityQueryServletPath=" + request.getServletPath());

		String customCityQuery = getCustomCityQuery(request);
		request.setAttribute("path",            request.getServletPath());
		request.setAttribute("cities",          getCities(customCityQuery));
		request.setAttribute("countries",       getCountries());
		request.setAttribute("customCityQuery", customCityQuery);
		request.getRequestDispatcher("customCityQuery.jsp").forward(request, response);
	}

	
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		
		request.setAttribute("customQuery", request.getParameter("query"));
		doGet(request, response);
	}



	// LOW LEVEL IMPLEMENTATION DETAILS
	
	private String getCustomCityQuery(HttpServletRequest request) {
		String customQuery   = (String) request.getAttribute("customQuery");
		String defaultQuery  = "SELECT *\nFROM city\nORDER BY Name ASC";
		return (customQuery == null) ? defaultQuery : customQuery;
	}
	

	private List<City> getCities(String query) {
		List<City> cities = null;
		try {
			cities = CityDAO.getInstance().getList(query);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return cities;
	}


	private List<Country> getCountries() {
		List<Country> countries = null;
		try {
			countries = CountryDAO.getInstance().getList();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return countries;
	}

}

src/main/java/com/github/bugtamer/controller/EditCityServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CityDAO;
import com.github.bugtamer.database.CountryDAO;
import com.github.bugtamer.database.DAO;
import com.github.bugtamer.models.City;
import com.github.bugtamer.models.Country;

@WebServlet("/editCity")
public class EditCityServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String id = request.getParameter("id");
		City city = getCity(id);
		if (city != null) {
			request.setAttribute("city", city);
		}
		request.setAttribute("path",        request.getServletPath());
		request.getRequestDispatcher("editCity.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String id          = request.getParameter("cid");
		String name        = request.getParameter("name");
		String countryCode = request.getParameter("countryCode");
		String district    = request.getParameter("district");
		String population  = request.getParameter("population");

		int iId         = (id == null) ? DAO.NO_ID : Integer.parseInt(id);
		int iPopulation = Integer.parseInt(population);

		if (iId != DAO.NO_ID) {
			City city = new City();
			city.setId(iId);
			city.setName(name);
			city.setCountry(getCountry(countryCode));
			city.setDistrict(district);
			city.setPopulation(iPopulation);
			update(city);
		}

		response.sendRedirect("cities");
	}



	// LOW LEVEL IMPLEMENTATION DETAILS

	private City getCity(String id) {
		City city = null;
		try {
			city = CityDAO.getInstance().getCityById(id);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return city;
	}


	private Country getCountry(String country) {
		Country c = null;
		try {
			c = CountryDAO.getInstance().getCountryByCode(country);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return c;
	}


	private int update(City city) {
		int rowCount = 0;
		try {
			rowCount = CityDAO.getInstance().update(city);
		} catch (Exception e) {
			e.printStackTrace();
		}

		System.out.println("rowCount=" + rowCount);
		return rowCount;
	}

}

src/main/java/com/github/bugtamer/controller/NewCityCountryServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CityCountryDAO;
import com.github.bugtamer.database.DAO;
import com.github.bugtamer.models.City;
import com.github.bugtamer.models.Country;

@WebServlet("/newCityCountry")
public class NewCityCountryServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		request.setAttribute("path", request.getServletPath());
		request.getRequestDispatcher("newCityCountry.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String name        = request.getParameter("name");
		String countryCode = request.getParameter("countryCode");
		String countryName = request.getParameter("countryName");
		String district    = request.getParameter("district");
		String population  = request.getParameter("population");

		int iPopulation = Integer.parseInt(population);

		Country country = new Country();
		country.setName(countryName);
		country.setCode(countryCode);

		City city = new City();
		city.setName(name);
		city.setCountry(country);
		city.setDistrict(district);
		city.setPopulation(iPopulation);

		int id = addCityAndItsCountry(city);

		if (id == DAO.NO_ID) {
			request.setAttribute("error", "ERROR: check city and country data.");
			request.setAttribute("city", city);
			doGet(request, response);
		} else {
			response.sendRedirect("editCity?id=" + id);
		}
	}



	// LOW LEVEL IMPLEMENTATION DETAILS

	private int addCityAndItsCountry(City city) {
		int id = DAO.NO_ID;
		try {
			id = CityCountryDAO.getInstance().addCityAndItsCountry(city);
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("...CAUSE BY:");
			e.getCause().printStackTrace();
		}
		System.out.println("id=" + id);
		return id;
	}

}

src/main/java/com/github/bugtamer/controller/NewCityServlet.java
package com.github.bugtamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.bugtamer.database.CityDAO;
import com.github.bugtamer.database.CountryDAO;
import com.github.bugtamer.database.DAO;
import com.github.bugtamer.models.City;
import com.github.bugtamer.models.Country;

@WebServlet("/newCity")
public class NewCityServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		request.setAttribute("path", request.getServletPath());
		request.getRequestDispatcher("newCity.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String name        = request.getParameter("name");
		String countryCode = request.getParameter("countryCode");
		String district    = request.getParameter("district");
		String population  = request.getParameter("population");

		int iPopulation = Integer.parseInt(population);

		City city = new City();
		city.setName(name);
		city.setCountry(getCountry(countryCode));
		city.setDistrict(district);
		city.setPopulation(iPopulation);

		int id = addCity(city);

		if (id == DAO.NO_ID) {
			request.setAttribute("error", "ERROR: comprueba los datos de la ciudad.");
			request.setAttribute("city", city);
			doGet(request, response);
		} else {
			response.sendRedirect("cities");
		}
	}



	// LOW LEVEL IMPLEMENTATION DETAILS

	private int addCity(City city) {
		int id = DAO.NO_ID;
		try {
			id = CityDAO.getInstance().add(city);
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("id=" + id);
		return id;
	}


	private Country getCountry(String country) {
		Country c = null;
		try {
			c = CountryDAO.getInstance().getCountryByCode(country);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return c;
	}

}

src/main/webapp/cities.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.github.bugtamer.models.Country" %><%-- <w:cityFilter/> --%>
<%@ page import="com.github.bugtamer.models.City" %><%-- <w:cityList/> --%>
<%@ taglib prefix="w" tagdir="/WEB-INF/tags" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>Cities</h2>
		<w:error/>
		<w:cityFilter/>
		<w:nav/>
		<w:cityList/>
	</div>
</body>
</html>

src/main/webapp/countries.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page import="com.github.bugtamer.models.Language" %>
<%@ page import="com.github.bugtamer.models.CountryLanguage" %>
<%@ page import="com.github.bugtamer.models.Country" %>
<%@ taglib prefix="w" tagdir="/WEB-INF/tags" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>Countries</h2>
		<w:nav/>
		<ul>
			<c:forEach var="country" items="${countries}">
			<li>${country.name}
				<ul>
					<li>Code: ${country.code}</li>
					<li>Lang: ${country.languages.size()}
						<ol>
							<c:forEach var="lang" items="${country.languages}">
							<li>${lang.name}
								<ul>
									<li>${lang.official ? "Official" : "NO official"}</li>
									<li>${lang.percentage}%</li>
								</ul>
							</li>
							</c:forEach>
						</ol>
					</li>
				</ul>
			</li>
			</c:forEach>
		</ul>
	</div>
</body>
</html>

src/main/webapp/customCityQuery.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.github.bugtamer.models.City" %><%-- <w:cityList/> --%>
<%@ taglib prefix="w" tagdir="/WEB-INF/tags" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>Cities</h2>
		<w:error/>
		<p>WARNING! only for: SELECT * FROM City</p>
		<w:customCityQuery/>
		<w:nav/>
		<w:cityList/>
	</div>
</body>
</html>

src/main/webapp/editCity.jsp
<%@ page import="com.github.bugtamer.models.City" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>Edit City</h2>
		<h3>${city.name}</h3>
		<h4>id=${city.id}</h4>

		<form action="./editCity" method="POST">
			<input name="cid"         type="hidden" placeholder="id"          value="${city.id}" /><br>
			<input name="name"        type="text"   placeholder="name"        value="${city.name}" /><br>
			<input name="countryCode" type="text"   placeholder="countryCode" value="${city.country.code}" /><br>
			<input name="district"    type="text"   placeholder="district"    value="${city.district}" /><br>
			<input name="population"  type="number" placeholder="population"  value="${city.population}" /><br>
			<button>Update</button>
			<br>
			<a href="./cities">go to Cities</a>
		</form>
	</div>
</body>
</html>

src/main/webapp/languages.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page import="com.github.bugtamer.models.CountryLanguage" %>
<%@ taglib prefix="w" tagdir="/WEB-INF/tags" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>Languages</h2>
		<form action="./languages" method="POST">
			<textarea id="query" name="query" cols="50" rows="5">${query}</textarea>
			<br>
			<button>Sumbit</button>
			<br>
		</form>
		<w:nav></w:nav>
		<ul>
			<c:forEach var="lang" items="${languages}">
			<li>
				${lang.language}
				<ul>
					<li>${lang.countryCode}</li>
					<li>Is official? ${lang.official}</li>
					<li>${lang.percentage}</li>
				</ul>
			</li>
			</c:forEach>
		</ul>
	</div>
</body>
</html>

src/main/webapp/newCity.jsp
<%@ page import="com.github.bugtamer.models.City" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>New City</h2>

		<form action="./newCity" method="POST">
			<input name="name"        type="text"   value="Fake name"      placeholder="name" /><br>
			<input name="countryCode" type="text"   value="AND"            placeholder="countryCode" /><br>
			<input name="district"    type="text"   value="Fake district" placeholder="district" /><br>
			<input name="population"  type="number" value="100"            placeholder="population"  /><br>
			<button>New</button>
			<br>
			<a href="./cities">go to Cities</a>
		</form>
		<p class="error">${error}</p>
	</div>
</body>
</html>

src/main/webapp/newCityCountry.jsp
<%@ taglib prefix="w" tagdir="/WEB-INF/tags" %>
<%@ page import="com.github.bugtamer.models.City" %>
<html>
<head>
	<link rel="stylesheet" href="./css/world.css">
</head>
<body>
	<div id="container">
		<h1>World</h1>
		<h2>New City and Country (Transactions)</h2>
		<w:nav/>

		<form action="./newCityCountry" method="POST">
			<h3>New city...</h3>
			<input name="name"        type="text"   value="Fake name"      placeholder="name" /><br>
			<input name="district"    type="text"   value="Fake district"  placeholder="district" /><br>
			<input name="population"  type="number" value="100"            placeholder="population"  /><br>
			<h3>...which belongs to this new Country</h3>
			<input name="countryCode" type="text"   value="AND"            placeholder="countryCode" /><br>
			<input name="countryName" type="text"   value="Andorra"        placeholder="country name" /><br>
			<button>New City and Country</button>
			<br>
		</form>
		<p class="error">${error}</p>
	</div>
</body>
</html>